name: Suspend SSAS Dev

on:
  workflow_dispatch:  
  schedule:
  - cron: "0 16 * * *"

jobs:
  Deploy:
    name: Suspend SSAS 
    uses: ./.github/workflows/template_release_dev.yml
    with:
      Environment: dev 
      DeploySSMS: false
      DeployADF: false
      DeploySSAS: false
      DeploySSASModel: "Template"
      SuspendSSAS: true
    secrets: inherit
