name: Suspend SSAS Test

on:
  workflow_dispatch:  
  schedule:
  - cron: "0 18 * * *"

jobs:
  Deploy:
    name: Release to test
    uses: ./.github/workflows/template_release_test.yml
    with:
      Environment: test 
      DeploySSMS: false
      DeployADF: false
      DeploySSAS: false
      DeploySSASModel: "Template"
      SuspendSSAS: true
    secrets: inherit
