name: Template tasks on Test

on:
  workflow_call:
    inputs:
      DeploySSMS:
        type: boolean
        description: Deploy SSMS
        default: false
        required: false
      DeployADF:
        type: boolean
        description: Deploy ADF
        default: false
        required: false
      DeploySSAS:
        type: boolean
        description: Deploy SSAS
        default: false
        required: false
      DeploySSASContentExplorer:
        type: boolean
        description: Deploy ContentExplorer
        default: false
      DeploySSASFaultManagement:
        type: boolean
        description: Deploy FaultManagmenet
        default: false
      DeploySSASProductExplorer:
        type: boolean
        description: Deploy ProductExplorer
        default: false
      SuspendSSAS:
        type: boolean
        description: Suspend SSAS
        default: false
        required: false

jobs:
  deploy:
    name: Run tasks on environment
    environment: test
    
    runs-on: windows-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@hf_447_release
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
        enable-AzPSSession: true  

    - name: Deploy SSMS
      if: ${{ inputs.DeploySSMS == true }}      
      uses: azure/sql-action@v2
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './SSMS/SSMS/SSMS.sqlproj'
        action: 'publish'
        build-arguments: '-c Release'                 # Optional build options passed to dotnet build

    - name: Deploy ADF
      if: ${{ inputs.DeployADF == true }} 
      uses: azure/powershell@v1
      with:
        inlineScript: |
            ./Automation/ADF/Deploy.ps1 -ResourceGroupName ${{ vars.AZURE_RESOURCE_GROUP_NAME }} -DataFactoryName ${{ vars.AZURE_ADF_NAME }} -IntegrationRuntimeName 'NuuDW-OnPremiseIntegrationRuntime' -Path "./ADF" -SubscriptionID ${{ vars.AZURE_SUBSCRIPTION_ID }} -ConnectionReplacements "" -TenantId ${{ vars.AZURE_TENANT_ID }}
        azPSVersion: "latest"
        
    - name: Resume SSAS
      if: ${{ inputs.DeploySSAS == true && inputs.Environment != 'dev'}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Automation/SSAS/ResumeAAS.ps1 -ResourceGroup ${{ vars.AZURE_RESOURCE_GROUP_NAME }} -SSASServer ${{ vars.AZURE_ANALYSIS_SERVER_NAME }}
        azPSVersion: "latest"
 
    - name: Build SSAS ContentExplorer
      if: ${{ inputs.DeploySSASContentExplorer == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Tools/TabularEditor/TabularEditor.exe ".\SSAS\ContentExplorer" -B ".\src\SSAS\ContentExplorer\ContentExplorer.bim"
        azPSVersion: "latest"        

    - name: Deploy SSAS ContentExplorer
      if: ${{ inputs.DeploySSASContentExplorer == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Tools/TabularEditor/TabularEditor.exe ".\SSAS\ContentExplorer" -S ".\Automation\SSAS\UpdateConnectionString.cs" -D "${{ secrets.ARM_SSAS_CONNECTION_STRING }}" "ContentExplorer" -C "|ConnectionString|" "${{ secrets.ARM_SQL_CONNECTION_STRING }}" -O -P -R -M -G -E
        azPSVersion: "latest"
 
    - name: Build SSAS FaultManagement
      if: ${{ inputs.DeploySSASFaultManagement == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Tools/TabularEditor/TabularEditor.exe ".\SSAS\FaultManagement" -B ".\src\SSAS\FaultManagement\FaultManagement.bim"
        azPSVersion: "latest"        

    - name: Deploy SSAS FaultManagement
      if: ${{ inputs.DeploySSASFaultManagement == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Tools/TabularEditor/TabularEditor.exe ".\SSAS\FaultManagement" -S ".\Automation\SSAS\UpdateConnectionString.cs" -D "${{ secrets.ARM_SSAS_CONNECTION_STRING }}" "FaultManagement" -C "|ConnectionString|" "${{ secrets.ARM_SQL_CONNECTION_STRING }}" -O -P -R -M -G -E
        azPSVersion: "latest"
 
    - name: Build SSAS ProductExplorer
      if: ${{ inputs.DeploySSASProductExplorer == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Tools/TabularEditor/TabularEditor.exe ".\SSAS\ProductExplorer" -B ".\src\SSAS\ProductExplorer\ProductExplorer.bim"
        azPSVersion: "latest"        

    - name: Deploy SSAS ProductExplorer
      if: ${{ inputs.DeploySSASProductExplorer == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Tools/TabularEditor/TabularEditor.exe ".\SSAS\ProductExplorer" -S ".\Automation\SSAS\UpdateConnectionString.cs" -D "${{ secrets.ARM_SSAS_CONNECTION_STRING }}" "ProductExplorer" -C "|ConnectionString|" "${{ secrets.ARM_SQL_CONNECTION_STRING }}" -O -P -R -M -G -E
        azPSVersion: "latest"

    - name: Suspend SSAS
      if: ${{ inputs.SuspendSSAS == true}}
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Automation/SSAS/SuspendAAS.ps1 -ResourceGroup ${{ vars.AZURE_RESOURCE_GROUP_NAME }} -SSASServer ${{ vars.AZURE_ANALYSIS_SERVER_NAME }}
        azPSVersion: "latest"


 

 
